project:
  title: "Carolina Rodriguez | Agriculture | Urban farming | sustainability"
  type: website
  output-dir: docs

website:
  site-url: "https://carolina-rodriguez.com"
  title: "Carolina Rodriguez"
  navbar:
    left:
      - href: about.qmd
        text: About me
      - icon: book
        href: research/index.qmd
        text: Research
      - href: publications.qmd
        text: Publications 
      - href: updates/index.qmd
        text: Updates

      
format:
  html:
    theme: 
      - Flatly
    css: 
      - styles.css
      - academicons.css
    toc: true
    
editor: visual


