---
title: "About me"
---

I do research on agroecology, and sustainable urban and rural farming systems, particularly in sustainable resource management. I currently work on enhancing the potential role of urban agriculture to support sustainable resource management and multifunctionality in urban environments as a postdoctoral researcher at the [Ecological and Environmental Modeling](https://liu.se/en/organisation/liu/ifm/ecomod) research group of Linköping University with my postdoctoral mentor [Geneviève Metson](https://liu.se/en/employee/genme46).

As a researcher, I include theories and methodologies in natural and social sciences that I apply in my current research. I focus on producing knowledge relevant to the transformation of both urban and rural farming systems. My research aims to support (urban) farmers through research, training interventions and co-design locally relevant production systems to build more sustainable management practices and develop more multifunctional urban and rural landscapes.

After my PhD studies, I had a short-term position as a Postdoc in the [Farming Systems Ecology](https://www.wur.nl/en/research-results/chair-groups/plant-sciences/farming-systems-ecology-group.htm) group at Wageningen University, performing a meta-analysis on diversified (intercropping) vegetable production systems.

I finished my doctoral studies at the Swedish University of Agricultural Sciences in the [Cropping Systems Ecology group](https://www.slu.se/en/departments/biosystems-technology/research/cropping-systems-ecology/). I focused on [crop diversification practices](https://pub.epsilon.slu.se/23741/1/rodriguez_c_210524.pdf) and the implications for resource use and cropping systems sustainability. I had the opportunity to visit the [INRA UNR agonomie](https://www6.versailles-grignon.inrae.fr/agronomie_eng/) in Thiverval-Grignon as a PhD student for one month in 2017. I have also been a member of the [European association for Agroecology](https://www.agroecology-europe.org/) since 2018.

A short CV can be downloaded [here](CV_RodriguezC.pdf)
